name: Build and Analyze
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # obligatoire pour une analyse complète

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # adapte si besoin

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=GuiguiLeGolem_poc-dice-game
            -Dsonar.organization=guiguilegolem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
